use std::time::Duration;

use cartograph_domain::ProjectId;
use serde::{Deserialize, Serialize};
use serde_json::{Map, Value};
use sqlx_core::{query::query, row::Row, sql_str::AssertSqlSafe};

use crate::{
    CartographDatabase, StorageError,
    database::{
        quoted_schema, set_local_statement_timeout, validate_bounded_limit as validate_limit,
        validate_json_object,
    },
};

const SESSION_TIMEOUT: Duration = Duration::from_secs(30);
const MAX_SESSION_LABEL_BYTES: usize = 256;
const MAX_SESSION_OBJECTIVE_BYTES: usize = 65_536;
const MAX_SESSION_LIST: u16 = 100;
const MAX_SESSION_CALLS: u16 = 1_000;
const MAX_RETAINED_TOOL_CALLS: i64 = 10_000;
const MAX_TOOL_NAME_BYTES: usize = 128;
const MAX_TOOL_ARGUMENT_BYTES: usize = 65_536;
const MAX_RESULT_SUMMARY_BYTES: usize = 2_048;
const MAX_MACRO_NAME_BYTES: usize = 256;
const MAX_MACRO_STEPS: usize = 32;
const MAX_MACRO_BYTES: usize = 256 * 1_024;
const MAX_MACRO_LIST: u16 = 100;

trait SessionListRecord: Sized {
    const MAXIMUM_LIMIT: u16;
    const OPERATION: &'static str;

    fn statement(schema: &str) -> String;
    fn decode(row: &sqlx_postgres::PgRow) -> Result<Self, StorageError>;
}

impl SessionListRecord for McpSessionRecord {
    const MAXIMUM_LIMIT: u16 = MAX_SESSION_LIST;
    const OPERATION: &'static str = "list-mcp-sessions";

    fn statement(schema: &str) -> String {
        format!(
            r#"SELECT session_id::text, label, objective, session_kind, state,
                      tool_count, started_at::text, last_activity_at::text
                FROM {schema}."mcp_sessions"
                WHERE project_id = CAST($1 AS uuid)
                ORDER BY last_activity_at DESC, id DESC
                LIMIT $2"#,
        )
    }

    fn decode(row: &sqlx_postgres::PgRow) -> Result<Self, StorageError> {
        decode_session(row)
    }
}

impl SessionListRecord for McpMacroRecord {
    const MAXIMUM_LIMIT: u16 = MAX_MACRO_LIST;
    const OPERATION: &'static str = "list-mcp-macros";

    fn statement(schema: &str) -> String {
        format!(
            r#"SELECT name, steps::text, created_at::text, updated_at::text,
                      last_run_at::text, run_count
                FROM {schema}."mcp_macros"
                WHERE project_id = CAST($1 AS uuid)
                ORDER BY updated_at DESC, name
                LIMIT $2"#,
        )
    }

    fn decode(row: &sqlx_postgres::PgRow) -> Result<Self, StorageError> {
        decode_macro(row)
    }
}

/// Durable session origin.
#[derive(Clone, Copy, Debug, PartialEq, Eq, Serialize)]
#[serde(rename_all = "snake_case")]
pub enum McpSessionKind {
    /// Session identity generated by Cartograph.
    Automatic,
    /// Caller-supplied, validated session identity.
    Named,
}

impl McpSessionKind {
    const fn as_str(self) -> &'static str {
        match self {
            Self::Automatic => "automatic",
            Self::Named => "named",
        }
    }

    fn parse(value: &str) -> Option<Self> {
        match value {
            "automatic" => Some(Self::Automatic),
            "named" => Some(Self::Named),
            _ => None,
        }
    }
}

/// Validated new durable trace session.
pub struct NewMcpSession {
    kind: McpSessionKind,
    label: Option<String>,
    objective: String,
}

impl NewMcpSession {
    #[must_use]
    /// Returns the automatic.
    pub fn automatic() -> Self {
        Self {
            kind: McpSessionKind::Automatic,
            label: None,
            objective: String::new(),
        }
    }

    /// Returns the named.
    ///
    /// # Errors
    ///
    /// Returns an error if `label` or `objective` is empty where required,
    /// oversized, or contains a NUL byte.
    pub fn named(label: &str, objective: &str) -> Result<Self, StorageError> {
        Self::named_optional(Some(label), objective)
    }

    /// Returns the named optional.
    ///
    /// # Errors
    ///
    /// Returns an error if the optional label or required objective violates
    /// its emptiness, byte-length, or NUL-byte contract.
    pub fn named_optional(label: Option<&str>, objective: &str) -> Result<Self, StorageError> {
        if let Some(label) = label {
            validate_label(label)?;
        }
        validate_objective(objective)?;
        Ok(Self {
            kind: McpSessionKind::Named,
            label: label.map(str::to_owned),
            objective: objective.to_owned(),
        })
    }
}

/// One durable MCP/agent investigation session.
#[derive(Clone, Debug, PartialEq, Eq, Serialize)]
#[serde(rename_all = "camelCase")]
pub struct McpSessionRecord {
    session_id: String,
    label: Option<String>,
    objective: String,
    kind: McpSessionKind,
    state: String,
    tool_count: u64,
    started_at: String,
    last_activity_at: String,
}

impl McpSessionRecord {
    #[must_use]
    /// Returns the session ID.
    pub fn session_id(&self) -> &str {
        &self.session_id
    }

    #[must_use]
    /// Returns the label.
    pub fn label(&self) -> Option<&str> {
        self.label.as_deref()
    }

    #[must_use]
    /// Returns the tool count.
    pub const fn tool_count(&self) -> u64 {
        self.tool_count
    }
}

/// Validated tool-call trace payload. Arguments must already be privacy-redacted.
pub struct McpToolCallInput {
    tool_name: String,
    arguments: Value,
    result_summary: String,
    success: bool,
    duration_ms: u64,
}

/// Privacy-redacted values for one validated tool-call trace.
pub struct McpToolCallData<'input> {
    /// Tool name for this record.
    pub tool_name: &'input str,
    /// Arguments for this record.
    pub arguments: Value,
    /// Result summary for this record.
    pub result_summary: &'input str,
    /// Whether this value is success.
    pub success: bool,
    /// Duration duration in milliseconds.
    pub duration_ms: u64,
}

impl McpToolCallInput {
    /// Creates a validated MCP tool call input.
    ///
    /// # Errors
    ///
    /// Returns an error if tool name/result text bounds fail or privacy-redacted
    /// arguments are not a bounded serializable JSON object.
    pub fn new(input: McpToolCallData<'_>) -> Result<Self, StorageError> {
        validate_tool_name(input.tool_name)?;
        validate_arguments(&input.arguments)?;
        validate_result_summary(input.result_summary)?;
        Ok(Self {
            tool_name: input.tool_name.to_owned(),
            arguments: input.arguments,
            result_summary: input.result_summary.to_owned(),
            success: input.success,
            duration_ms: input.duration_ms,
        })
    }
}

/// Exact or fallback lookup for one project-owned MCP session.
pub struct McpSessionLookup<'lookup> {
    /// Stable project ID for this record.
    pub project_id: &'lookup ProjectId,
    /// Optional session ID, when available.
    pub session_id: Option<&'lookup str>,
    /// Optional label, when available.
    pub label: Option<&'lookup str>,
    /// Whether this value is require calls.
    pub require_calls: bool,
}

/// Atomic append request for one validated tool call.
pub struct McpToolCallWrite<'write> {
    /// Stable project ID for this record.
    pub project_id: &'write ProjectId,
    /// Stable session ID for this record.
    pub session_id: &'write str,
    /// Input for this record.
    pub input: &'write McpToolCallInput,
}

/// Bounded ordered trace query for one session.
pub struct McpSessionCallsQuery<'query> {
    /// Stable project ID for this record.
    pub project_id: &'query ProjectId,
    /// Stable session ID for this record.
    pub session_id: &'query str,
    /// Maximum number of entries returned by this bounded request.
    pub limit: u16,
}

#[derive(Clone, Copy)]
struct TextValidation<'value> {
    value: &'value str,
    maximum: usize,
    field: &'static str,
    allow_empty: bool,
}

enum SessionReadBindings<'binding> {
    None,
    Limit(u16),
    Text(&'binding str),
    Calls {
        session_id: &'binding str,
        limit: u16,
    },
    Lookup {
        session_id: Option<&'binding str>,
        label: Option<&'binding str>,
        require_calls: bool,
    },
}

struct SessionReadInput<'project> {
    statement: String,
    bindings: SessionReadBindings<'project>,
    project_id: &'project ProjectId,
    operation: &'static str,
}

/// One ordered call from a durable session trace.
#[derive(Clone, Debug, PartialEq, Eq, Serialize)]
#[serde(rename_all = "camelCase")]
pub struct McpToolCallRecord {
    session_id: String,
    step: u64,
    called_at: String,
    tool_name: String,
    arguments: Value,
    result_summary: String,
    success: bool,
    duration_ms: u64,
}

impl McpToolCallRecord {
    #[must_use]
    /// Returns the step.
    pub const fn step(&self) -> u64 {
        self.step
    }

    #[must_use]
    /// Returns the tool name.
    pub fn tool_name(&self) -> &str {
        &self.tool_name
    }

    #[must_use]
    /// Returns the arguments.
    pub const fn arguments(&self) -> &Value {
        &self.arguments
    }

    #[must_use]
    /// Returns the result summary.
    pub fn result_summary(&self) -> &str {
        &self.result_summary
    }

    #[must_use]
    /// Returns the success.
    pub const fn success(&self) -> bool {
        self.success
    }

    #[must_use]
    /// Returns the duration milliseconds.
    pub const fn duration_ms(&self) -> u64 {
        self.duration_ms
    }
}

/// Aggregate latency/use row for one MCP tool.
#[derive(Clone, Debug, PartialEq, Eq, Serialize)]
#[serde(rename_all = "camelCase")]
pub struct McpToolUsage {
    tool_name: String,
    call_count: u64,
    p50_duration_ms: u64,
    p95_duration_ms: u64,
    max_duration_ms: u64,
}

/// Project-local trace totals and per-tool latency percentiles.
#[derive(Clone, Debug, PartialEq, Eq, Serialize)]
#[serde(rename_all = "camelCase")]
pub struct McpTraceUsage {
    session_count: u64,
    tool_call_count: u64,
    error_count: u64,
    tools: Vec<McpToolUsage>,
}

/// One validated saved macro step.
#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct McpMacroStep {
    tool: String,
    #[serde(default)]
    args: Map<String, Value>,
}

impl McpMacroStep {
    /// Creates a validated MCP macro step.
    ///
    /// # Errors
    ///
    /// Returns an error if the tool name is invalid or the argument object is
    /// not serializable within the trace payload byte bound.
    pub fn new(tool: &str, args: Map<String, Value>) -> Result<Self, StorageError> {
        validate_tool_name(tool)?;
        validate_arguments(&Value::Object(args.clone()))?;
        Ok(Self {
            tool: tool.to_owned(),
            args,
        })
    }

    #[must_use]
    /// Returns the tool.
    pub fn tool(&self) -> &str {
        &self.tool
    }

    #[must_use]
    /// Returns the args.
    pub const fn args(&self) -> &Map<String, Value> {
        &self.args
    }
}

/// Validated macro upsert.
pub struct NewMcpMacro {
    name: String,
    steps: Vec<McpMacroStep>,
}

impl NewMcpMacro {
    /// Creates a validated new MCP macro.
    ///
    /// # Errors
    ///
    /// Returns an error if the macro name or step count is invalid, or any
    /// validated step would exceed the aggregate recipe bound.
    pub fn new(name: &str, steps: Vec<McpMacroStep>) -> Result<Self, StorageError> {
        validate_macro_name(name)?;
        validate_macro_steps(&steps)?;
        Ok(Self {
            name: name.to_owned(),
            steps,
        })
    }
}

/// One durable macro recipe and execution metadata.
#[derive(Clone, Debug, PartialEq, Serialize)]
#[serde(rename_all = "camelCase")]
pub struct McpMacroRecord {
    name: String,
    steps: Vec<McpMacroStep>,
    created_at: String,
    updated_at: String,
    last_run_at: Option<String>,
    run_count: u64,
}

impl McpMacroRecord {
    #[must_use]
    /// Returns the name.
    pub fn name(&self) -> &str {
        &self.name
    }

    #[must_use]
    /// Returns the steps.
    pub fn steps(&self) -> &[McpMacroStep] {
        &self.steps
    }
}

impl CartographDatabase {
    /// Create an automatic process trace or named resumable session.
    /// # Errors
    ///
    /// Returns an error if label/objective validation fails or the inserted
    /// session row cannot be queried or decoded.
    pub async fn create_mcp_session(
        &self,
        project_id: &ProjectId,
        input: &NewMcpSession,
    ) -> Result<McpSessionRecord, StorageError> {
        if let Some(label) = &input.label {
            validate_label(label)?;
        }
        validate_objective(&input.objective)?;
        let schema = quoted_schema(&self.schema);
        let statement = format!(
            r#"INSERT INTO {schema}."mcp_sessions" (
                    project_id, label, objective, session_kind
                ) VALUES (CAST($1 AS uuid), $2, $3, $4)
                RETURNING session_id::text, label, objective, session_kind, state,
                          tool_count, started_at::text, last_activity_at::text"#,
        );
        let row = query(AssertSqlSafe(statement))
            .bind(project_id.as_str())
            .bind(input.label.as_deref())
            .bind(&input.objective)
            .bind(input.kind.as_str())
            .fetch_one(&self.pool)
            .await
            .map_err(|_| database_error("create-mcp-session"))?;
        decode_session(&row)
    }

    /// List newest active/closed sessions for one project.
    /// # Errors
    ///
    /// Returns an error if `limit` is invalid or a newest-first session row
    /// cannot be queried or decoded.
    pub async fn list_mcp_sessions(
        &self,
        project_id: &ProjectId,
        limit: u16,
    ) -> Result<Vec<McpSessionRecord>, StorageError> {
        self.list_session_records(project_id, limit).await
    }

    /// Resolve a project-owned session by exact UUID, newest label, or latest non-empty trace.
    /// # Errors
    ///
    /// Returns an error if no lookup discriminator is supplied, UUID/label
    /// validation fails, or the matching session row is malformed.
    pub async fn find_mcp_session(
        &self,
        lookup: McpSessionLookup<'_>,
    ) -> Result<Option<McpSessionRecord>, StorageError> {
        if lookup.session_id.is_none() && lookup.label.is_none() && !lookup.require_calls {
            return Err(StorageError::InvalidInput {
                field: "session_lookup",
            });
        }
        if let Some(session_id) = lookup.session_id {
            validate_uuid(session_id, "session_id")?;
        }
        if let Some(label) = lookup.label {
            validate_label(label)?;
        }
        let schema = quoted_schema(&self.schema);
        let statement = format!(
            r#"SELECT session_id::text, label, objective, session_kind, state,
                      tool_count, started_at::text, last_activity_at::text
                FROM {schema}."mcp_sessions"
                WHERE project_id = CAST($1 AS uuid)
                  AND ($2::text IS NULL OR session_id = CAST($2 AS uuid))
                  AND ($2::text IS NOT NULL OR $3::text IS NULL OR label = $3)
                  AND (NOT $4::boolean OR tool_count > 0)
                ORDER BY last_activity_at DESC, id DESC
                LIMIT 1"#,
        );
        let rows = self
            .session_read(SessionReadInput {
                statement,
                bindings: SessionReadBindings::Lookup {
                    session_id: lookup.session_id,
                    label: lookup.label,
                    require_calls: lookup.require_calls,
                },
                project_id: lookup.project_id,
                operation: "find-mcp-session",
            })
            .await?;
        rows.first().map(decode_session).transpose()
    }

    /// Delete a session and all calls under its foreign-key cascade.
    /// # Errors
    ///
    /// Returns an error if `session_id` is not a UUID or the project-scoped
    /// session cascade cannot be deleted.
    pub async fn delete_mcp_session(
        &self,
        project_id: &ProjectId,
        session_id: &str,
    ) -> Result<bool, StorageError> {
        validate_uuid(session_id, "session_id")?;
        let schema = quoted_schema(&self.schema);
        let statement = format!(
            r#"DELETE FROM {schema}."mcp_sessions"
                WHERE project_id = CAST($1 AS uuid)
                  AND session_id = CAST($2 AS uuid)"#,
        );
        let result = query(AssertSqlSafe(statement))
            .bind(project_id.as_str())
            .bind(session_id)
            .execute(&self.pool)
            .await
            .map_err(|_| database_error("delete-mcp-session"))?;
        Ok(result.rows_affected() == 1)
    }

    /// Atomically allocate a step, append a trace row, and prune oldest project calls.
    /// # Errors
    ///
    /// Returns an error if session/tool-call validation fails, the session is
    /// missing, or step allocation, insertion, pruning, and commit are not atomic.
    pub async fn record_mcp_tool_call(
        &self,
        request: McpToolCallWrite<'_>,
    ) -> Result<McpToolCallRecord, StorageError> {
        validate_uuid(request.session_id, "session_id")?;
        validate_tool_call(request.input)?;
        let schema = quoted_schema(&self.schema);
        let mut transaction = self
            .pool
            .begin()
            .await
            .map_err(|_| database_error("begin-record-mcp-call"))?;
        set_local_statement_timeout(&mut transaction, SESSION_TIMEOUT)
            .await
            .map_err(|()| database_error("timeout-record-mcp-call"))?;
        let update = format!(
            r#"UPDATE {schema}."mcp_sessions"
                SET tool_count = tool_count + 1,
                    last_activity_at = clock_timestamp()
                WHERE project_id = CAST($1 AS uuid)
                  AND session_id = CAST($2 AS uuid)
                RETURNING tool_count"#,
        );
        let step = query(AssertSqlSafe(update))
            .bind(request.project_id.as_str())
            .bind(request.session_id)
            .fetch_optional(&mut *transaction)
            .await
            .map_err(|_| database_error("allocate-mcp-call-step"))?
            .ok_or(StorageError::InvalidInput {
                field: "session_id",
            })?
            .try_get::<i64, _>(0)
            .map_err(|_| StorageError::CorruptStoredValue {
                field: "session_step",
            })?;
        let arguments = serde_json::to_string(&request.input.arguments).map_err(|_| {
            StorageError::InvalidInput {
                field: "tool_arguments",
            }
        })?;
        let insert = format!(
            r#"INSERT INTO {schema}."mcp_tool_calls" (
                    project_id, session_id, step, tool_name, arguments,
                    result_summary, result_kind, duration_ms
                ) VALUES (
                    CAST($1 AS uuid), CAST($2 AS uuid), $3, $4,
                    CAST($5 AS jsonb), $6, $7, $8
                )
                RETURNING session_id::text, step, called_at::text, tool_name,
                          arguments::text, result_summary, result_kind, duration_ms"#,
        );
        let row = query(AssertSqlSafe(insert))
            .bind(request.project_id.as_str())
            .bind(request.session_id)
            .bind(step)
            .bind(&request.input.tool_name)
            .bind(arguments)
            .bind(&request.input.result_summary)
            .bind(if request.input.success {
                "success"
            } else {
                "error"
            })
            .bind(i64::try_from(request.input.duration_ms).map_err(|_| {
                StorageError::InvalidInput {
                    field: "duration_ms",
                }
            })?)
            .fetch_one(&mut *transaction)
            .await
            .map_err(|_| database_error("insert-mcp-call"))?;
        let prune = format!(
            r#"DELETE FROM {schema}."mcp_tool_calls"
                WHERE id IN (
                    SELECT id
                    FROM {schema}."mcp_tool_calls"
                    WHERE project_id = CAST($1 AS uuid)
                    ORDER BY called_at DESC, id DESC
                    OFFSET {MAX_RETAINED_TOOL_CALLS}
                )"#,
        );
        query(AssertSqlSafe(prune))
            .bind(request.project_id.as_str())
            .execute(&mut *transaction)
            .await
            .map_err(|_| database_error("prune-mcp-calls"))?;
        transaction
            .commit()
            .await
            .map_err(|_| database_error("commit-record-mcp-call"))?;
        decode_call(&row)
    }

    /// Return one session's ordered bounded trace.
    /// # Errors
    ///
    /// Returns an error if session UUID/result limit validation fails or an
    /// ordered trace row cannot be queried or decoded.
    pub async fn mcp_calls_for_session(
        &self,
        request: McpSessionCallsQuery<'_>,
    ) -> Result<Vec<McpToolCallRecord>, StorageError> {
        validate_uuid(request.session_id, "session_id")?;
        validate_limit(request.limit, MAX_SESSION_CALLS)?;
        let schema = quoted_schema(&self.schema);
        let statement = format!(
            r#"SELECT session_id::text, step, called_at::text, tool_name,
                      arguments::text, result_summary, result_kind, duration_ms
                FROM (
                    SELECT session_id, step, called_at, tool_name, arguments,
                           result_summary, result_kind, duration_ms
                    FROM {schema}."mcp_tool_calls"
                    WHERE project_id = CAST($1 AS uuid)
                      AND session_id = CAST($2 AS uuid)
                    ORDER BY step DESC
                    LIMIT $3
                ) AS recent
                ORDER BY step"#,
        );
        let rows = self
            .session_read(SessionReadInput {
                statement,
                bindings: SessionReadBindings::Calls {
                    session_id: request.session_id,
                    limit: request.limit,
                },
                project_id: request.project_id,
                operation: "mcp-calls-for-session",
            })
            .await?;
        rows.iter().map(decode_call).collect()
    }

    /// Aggregate trace counts and exact PostgreSQL discrete latency percentiles.
    /// # Errors
    ///
    /// Returns an error if aggregate counts/latency percentiles cannot be
    /// queried or any stored value is negative, malformed, or overflowing.
    pub async fn mcp_trace_usage(
        &self,
        project_id: &ProjectId,
    ) -> Result<McpTraceUsage, StorageError> {
        let schema = quoted_schema(&self.schema);
        let totals = format!(
            r#"SELECT
                    (SELECT COUNT(*) FROM {schema}."mcp_sessions"
                     WHERE project_id = CAST($1 AS uuid))::bigint,
                    COUNT(*)::bigint,
                    COUNT(*) FILTER (WHERE result_kind = 'error')::bigint
                FROM {schema}."mcp_tool_calls"
                WHERE project_id = CAST($1 AS uuid)"#,
        );
        let rows = self
            .session_read(SessionReadInput {
                statement: totals,
                bindings: SessionReadBindings::None,
                project_id,
                operation: "mcp-trace-usage-totals",
            })
            .await?;
        let row = rows.first().ok_or(StorageError::CorruptStoredValue {
            field: "trace_usage",
        })?;
        let session_count = nonnegative_u64(row, 0)?;
        let tool_call_count = nonnegative_u64(row, 1)?;
        let error_count = nonnegative_u64(row, 2)?;
        let by_tool = format!(
            r#"SELECT tool_name,
                      COUNT(*)::bigint,
                      percentile_disc(0.50) WITHIN GROUP (ORDER BY duration_ms)::bigint,
                      percentile_disc(0.95) WITHIN GROUP (ORDER BY duration_ms)::bigint,
                      MAX(duration_ms)::bigint
                FROM {schema}."mcp_tool_calls"
                WHERE project_id = CAST($1 AS uuid)
                GROUP BY tool_name
                ORDER BY COUNT(*) DESC, tool_name"#,
        );
        let tools = self
            .session_read(SessionReadInput {
                statement: by_tool,
                bindings: SessionReadBindings::None,
                project_id,
                operation: "mcp-trace-usage-tools",
            })
            .await?
            .iter()
            .map(|row| {
                Ok(McpToolUsage {
                    tool_name: text(row, 0)?,
                    call_count: nonnegative_u64(row, 1)?,
                    p50_duration_ms: nonnegative_u64(row, 2)?,
                    p95_duration_ms: nonnegative_u64(row, 3)?,
                    max_duration_ms: nonnegative_u64(row, 4)?,
                })
            })
            .collect::<Result<Vec<_>, StorageError>>()?;
        Ok(McpTraceUsage {
            session_count,
            tool_call_count,
            error_count,
            tools,
        })
    }

    /// Upsert one validated project-local macro recipe.
    /// # Errors
    ///
    /// Returns an error if macro validation/JSON encoding fails or the upserted
    /// recipe and usage metadata cannot be decoded.
    pub async fn save_mcp_macro(
        &self,
        project_id: &ProjectId,
        input: &NewMcpMacro,
    ) -> Result<McpMacroRecord, StorageError> {
        validate_macro_name(&input.name)?;
        validate_macro_steps(&input.steps)?;
        let schema = quoted_schema(&self.schema);
        let steps =
            serde_json::to_string(&input.steps).map_err(|_| StorageError::InvalidInput {
                field: "macro_steps",
            })?;
        let statement = format!(
            r#"INSERT INTO {schema}."mcp_macros" (project_id, name, steps)
                VALUES (CAST($1 AS uuid), $2, CAST($3 AS jsonb))
                ON CONFLICT (project_id, name) DO UPDATE
                SET steps = EXCLUDED.steps,
                    updated_at = clock_timestamp()
                RETURNING name, steps::text, created_at::text, updated_at::text,
                          last_run_at::text, run_count"#,
        );
        let row = query(AssertSqlSafe(statement))
            .bind(project_id.as_str())
            .bind(&input.name)
            .bind(steps)
            .fetch_one(&self.pool)
            .await
            .map_err(|_| database_error("save-mcp-macro"))?;
        decode_macro(&row)
    }

    /// Resolve one exact macro name.
    /// # Errors
    ///
    /// Returns an error if `name` violates macro bounds or the stored recipe
    /// cannot be queried, parsed, or validated.
    pub async fn get_mcp_macro(
        &self,
        project_id: &ProjectId,
        name: &str,
    ) -> Result<Option<McpMacroRecord>, StorageError> {
        validate_macro_name(name)?;
        let schema = quoted_schema(&self.schema);
        let statement = format!(
            r#"SELECT name, steps::text, created_at::text, updated_at::text,
                      last_run_at::text, run_count
                FROM {schema}."mcp_macros"
                WHERE project_id = CAST($1 AS uuid) AND name = $2"#,
        );
        let rows = self
            .session_read(SessionReadInput {
                statement,
                bindings: SessionReadBindings::Text(name),
                project_id,
                operation: "get-mcp-macro",
            })
            .await?;
        rows.first().map(decode_macro).transpose()
    }

    /// List saved macros newest-first.
    /// # Errors
    ///
    /// Returns an error if `limit` is invalid or a newest-first macro recipe
    /// cannot be queried, parsed, or validated.
    pub async fn list_mcp_macros(
        &self,
        project_id: &ProjectId,
        limit: u16,
    ) -> Result<Vec<McpMacroRecord>, StorageError> {
        self.list_session_records(project_id, limit).await
    }

    /// Increment successful macro-run usage metadata.
    /// # Errors
    ///
    /// Returns an error if `name` violates macro bounds or PostgreSQL cannot
    /// update its run timestamp/count.
    pub async fn mark_mcp_macro_run(
        &self,
        project_id: &ProjectId,
        name: &str,
    ) -> Result<(), StorageError> {
        validate_macro_name(name)?;
        let schema = quoted_schema(&self.schema);
        let statement = format!(
            r#"UPDATE {schema}."mcp_macros"
                SET last_run_at = clock_timestamp(), run_count = run_count + 1
                WHERE project_id = CAST($1 AS uuid) AND name = $2"#,
        );
        query(AssertSqlSafe(statement))
            .bind(project_id.as_str())
            .bind(name)
            .execute(&self.pool)
            .await
            .map_err(|_| database_error("mark-mcp-macro-run"))?;
        Ok(())
    }

    /// Delete one exact macro name.
    /// # Errors
    ///
    /// Returns an error if `name` violates macro bounds or PostgreSQL cannot
    /// delete the project-scoped recipe.
    pub async fn delete_mcp_macro(
        &self,
        project_id: &ProjectId,
        name: &str,
    ) -> Result<bool, StorageError> {
        validate_macro_name(name)?;
        let schema = quoted_schema(&self.schema);
        let statement = format!(
            r#"DELETE FROM {schema}."mcp_macros"
                WHERE project_id = CAST($1 AS uuid) AND name = $2"#,
        );
        let result = query(AssertSqlSafe(statement))
            .bind(project_id.as_str())
            .bind(name)
            .execute(&self.pool)
            .await
            .map_err(|_| database_error("delete-mcp-macro"))?;
        Ok(result.rows_affected() == 1)
    }

    async fn list_session_records<Record>(
        &self,
        project_id: &ProjectId,
        limit: u16,
    ) -> Result<Vec<Record>, StorageError>
    where
        Record: SessionListRecord,
    {
        validate_limit(limit, Record::MAXIMUM_LIMIT)?;
        let schema = quoted_schema(&self.schema);
        let rows = self
            .session_read(SessionReadInput {
                statement: Record::statement(&schema),
                bindings: SessionReadBindings::Limit(limit),
                project_id,
                operation: Record::OPERATION,
            })
            .await?;
        rows.iter().map(Record::decode).collect()
    }

    async fn session_read(
        &self,
        input: SessionReadInput<'_>,
    ) -> Result<Vec<sqlx_postgres::PgRow>, StorageError> {
        let mut transaction = self
            .pool
            .begin()
            .await
            .map_err(|_| database_error(input.operation))?;
        query("SET TRANSACTION READ ONLY")
            .execute(&mut *transaction)
            .await
            .map_err(|_| database_error(input.operation))?;
        set_local_statement_timeout(&mut transaction, SESSION_TIMEOUT)
            .await
            .map_err(|()| database_error(input.operation))?;
        let statement = query(AssertSqlSafe(input.statement)).bind(input.project_id.as_str());
        let rows = match input.bindings {
            SessionReadBindings::None => statement.fetch_all(&mut *transaction).await,
            SessionReadBindings::Limit(limit) => {
                statement
                    .bind(i64::from(limit))
                    .fetch_all(&mut *transaction)
                    .await
            }
            SessionReadBindings::Text(value) => {
                statement.bind(value).fetch_all(&mut *transaction).await
            }
            SessionReadBindings::Calls { session_id, limit } => {
                statement
                    .bind(session_id)
                    .bind(i64::from(limit))
                    .fetch_all(&mut *transaction)
                    .await
            }
            SessionReadBindings::Lookup {
                session_id,
                label,
                require_calls,
            } => {
                statement
                    .bind(session_id)
                    .bind(label)
                    .bind(require_calls)
                    .fetch_all(&mut *transaction)
                    .await
            }
        }
        .map_err(|_| database_error(input.operation))?;
        transaction
            .commit()
            .await
            .map_err(|_| database_error(input.operation))?;
        Ok(rows)
    }
}

fn validate_label(value: &str) -> Result<(), StorageError> {
    validate_text(TextValidation {
        value,
        maximum: MAX_SESSION_LABEL_BYTES,
        field: "session_label",
        allow_empty: false,
    })
}

fn validate_objective(value: &str) -> Result<(), StorageError> {
    validate_text(TextValidation {
        value,
        maximum: MAX_SESSION_OBJECTIVE_BYTES,
        field: "session_objective",
        allow_empty: true,
    })
}

fn validate_tool_name(value: &str) -> Result<(), StorageError> {
    validate_text(TextValidation {
        value,
        maximum: MAX_TOOL_NAME_BYTES,
        field: "tool_name",
        allow_empty: false,
    })?;
    if value
        .bytes()
        .all(|byte| byte.is_ascii_alphanumeric() || matches!(byte, b'_' | b'-' | b'.'))
    {
        Ok(())
    } else {
        Err(StorageError::InvalidInput { field: "tool_name" })
    }
}

fn validate_arguments(value: &Value) -> Result<(), StorageError> {
    validate_json_object(value, MAX_TOOL_ARGUMENT_BYTES, "tool_arguments")
}

fn validate_result_summary(value: &str) -> Result<(), StorageError> {
    validate_text(TextValidation {
        value,
        maximum: MAX_RESULT_SUMMARY_BYTES,
        field: "result_summary",
        allow_empty: true,
    })
}

fn validate_tool_call(input: &McpToolCallInput) -> Result<(), StorageError> {
    validate_tool_name(&input.tool_name)?;
    validate_arguments(&input.arguments)?;
    validate_result_summary(&input.result_summary)
}

fn validate_macro_name(value: &str) -> Result<(), StorageError> {
    validate_text(TextValidation {
        value,
        maximum: MAX_MACRO_NAME_BYTES,
        field: "macro_name",
        allow_empty: false,
    })
}

fn validate_macro_steps(steps: &[McpMacroStep]) -> Result<(), StorageError> {
    if steps.is_empty() || steps.len() > MAX_MACRO_STEPS {
        return Err(StorageError::InvalidInput {
            field: "macro_steps",
        });
    }
    for step in steps {
        validate_tool_name(&step.tool)?;
        validate_arguments(&Value::Object(step.args.clone()))?;
    }
    let encoded = serde_json::to_vec(steps).map_err(|_| StorageError::InvalidInput {
        field: "macro_steps",
    })?;
    if encoded.len() > MAX_MACRO_BYTES {
        Err(StorageError::InvalidInput {
            field: "macro_steps",
        })
    } else {
        Ok(())
    }
}

fn validate_text(input: TextValidation<'_>) -> Result<(), StorageError> {
    if (!input.allow_empty && input.value.is_empty())
        || input.value.len() > input.maximum
        || input.value.contains('\0')
    {
        Err(StorageError::InvalidInput { field: input.field })
    } else {
        Ok(())
    }
}

fn validate_uuid(value: &str, field: &'static str) -> Result<(), StorageError> {
    let valid = value.len() == 36
        && value.bytes().enumerate().all(|(index, byte)| {
            if matches!(index, 8 | 13 | 18 | 23) {
                byte == b'-'
            } else {
                byte.is_ascii_hexdigit()
            }
        });
    valid.ok_or(StorageError::InvalidInput { field })
}

const SESSION_KIND_COLUMN: usize = 3;
const SESSION_STATE_COLUMN: usize = 4;
const SESSION_TOOL_COUNT_COLUMN: usize = 5;
const SESSION_STARTED_AT_COLUMN: usize = 6;
const SESSION_LAST_ACTIVITY_COLUMN: usize = 7;
const CALL_ARGUMENTS_COLUMN: usize = 4;
const CALL_RESULT_SUMMARY_COLUMN: usize = 5;
const CALL_RESULT_KIND_COLUMN: usize = 6;
const CALL_DURATION_COLUMN: usize = 7;
const MACRO_UPDATED_AT_COLUMN: usize = 3;
const MACRO_LAST_RUN_AT_COLUMN: usize = 4;
const MACRO_RUN_COUNT_COLUMN: usize = 5;

fn decode_session(row: &sqlx_postgres::PgRow) -> Result<McpSessionRecord, StorageError> {
    Ok(McpSessionRecord {
        session_id: text(row, 0)?,
        label: optional_text(row, 1)?,
        objective: text(row, 2)?,
        kind: McpSessionKind::parse(&text(row, SESSION_KIND_COLUMN)?).ok_or(
            StorageError::CorruptStoredValue {
                field: "session_kind",
            },
        )?,
        state: text(row, SESSION_STATE_COLUMN)?,
        tool_count: nonnegative_u64(row, SESSION_TOOL_COUNT_COLUMN)?,
        started_at: text(row, SESSION_STARTED_AT_COLUMN)?,
        last_activity_at: text(row, SESSION_LAST_ACTIVITY_COLUMN)?,
    })
}

fn decode_call(row: &sqlx_postgres::PgRow) -> Result<McpToolCallRecord, StorageError> {
    let arguments =
        serde_json::from_str::<Value>(&text(row, CALL_ARGUMENTS_COLUMN)?).map_err(|_| {
            StorageError::CorruptStoredValue {
                field: "tool_arguments",
            }
        })?;
    Ok(McpToolCallRecord {
        session_id: text(row, 0)?,
        step: nonnegative_u64(row, 1)?,
        called_at: text(row, 2)?,
        tool_name: text(row, SESSION_KIND_COLUMN)?,
        arguments,
        result_summary: text(row, CALL_RESULT_SUMMARY_COLUMN)?,
        success: match text(row, CALL_RESULT_KIND_COLUMN)?.as_str() {
            "success" => true,
            "error" => false,
            _ => {
                return Err(StorageError::CorruptStoredValue {
                    field: "result_kind",
                });
            }
        },
        duration_ms: nonnegative_u64(row, CALL_DURATION_COLUMN)?,
    })
}

fn decode_macro(row: &sqlx_postgres::PgRow) -> Result<McpMacroRecord, StorageError> {
    let steps = serde_json::from_str::<Vec<McpMacroStep>>(&text(row, 1)?).map_err(|_| {
        StorageError::CorruptStoredValue {
            field: "macro_steps",
        }
    })?;
    validate_macro_steps(&steps).map_err(|_| StorageError::CorruptStoredValue {
        field: "macro_steps",
    })?;
    Ok(McpMacroRecord {
        name: text(row, 0)?,
        steps,
        created_at: text(row, 2)?,
        updated_at: text(row, MACRO_UPDATED_AT_COLUMN)?,
        last_run_at: optional_text(row, MACRO_LAST_RUN_AT_COLUMN)?,
        run_count: nonnegative_u64(row, MACRO_RUN_COUNT_COLUMN)?,
    })
}

fn text(row: &sqlx_postgres::PgRow, index: usize) -> Result<String, StorageError> {
    row.try_get(index)
        .map_err(|_| StorageError::CorruptStoredValue { field: "session" })
}

fn optional_text(row: &sqlx_postgres::PgRow, index: usize) -> Result<Option<String>, StorageError> {
    row.try_get(index)
        .map_err(|_| StorageError::CorruptStoredValue { field: "session" })
}

fn nonnegative_u64(row: &sqlx_postgres::PgRow, index: usize) -> Result<u64, StorageError> {
    let value = row
        .try_get::<i64, _>(index)
        .map_err(|_| StorageError::CorruptStoredValue { field: "session" })?;
    u64::try_from(value).map_err(|_| StorageError::CorruptStoredValue { field: "session" })
}

const fn database_error(operation: &'static str) -> StorageError {
    StorageError::DatabaseOperation { operation }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn macro_contract_rejects_empty_and_oversized_recipes() {
        assert!(NewMcpMacro::new("empty", Vec::new()).is_err());
        let step = McpMacroStep::new("cartograph_status", Map::new())
            .unwrap_or_else(|error| panic!("macro step failed: {error}"));
        assert!(NewMcpMacro::new("valid", vec![step.clone()]).is_ok());
        assert!(NewMcpMacro::new("too-many", vec![step; MAX_MACRO_STEPS + 1]).is_err());
    }

    #[test]
    fn trace_arguments_must_be_bounded_objects() {
        assert!(
            McpToolCallInput::new(McpToolCallData {
                tool_name: "cartograph_status",
                arguments: Value::Null,
                result_summary: "ok",
                success: true,
                duration_ms: 1,
            })
            .is_err()
        );
        assert!(
            McpToolCallInput::new(McpToolCallData {
                tool_name: "cartograph_status",
                arguments: Value::Object(Map::new()),
                result_summary: "ok",
                success: true,
                duration_ms: 1,
            })
            .is_ok()
        );
    }
}
