export function renderGuide(): string {
  return [
    '## cartograph guide',
    '',
    '### First run',
    '',
    '```sh',
    'cartograph install --yes --location=local   # agent setup: MCP config + init + index + git hooks',
    'cartograph index .                          # index only (no agent wiring)',
    'cartograph status --verbose .',
    'cartograph viewer .',
    '```',
    '',
    '### Daily coding loop',
    '',
    '```sh',
    'cartograph find "SymbolName" --mode fuzzy',
    'cartograph graph SymbolName --direction impact',
    'cartograph files --format symbols --file src/path/to/file.ts',
    'cartograph affected --include-commands',
    '```',
    '',
    '### LLM-backed features',
    '',
    '```sh',
    'cartograph llm install .   # recommended local stack: models + config + doctor',
    'cartograph admin llm-plan .',
    'cartograph admin llm-apply --preset <id> .',
    'cartograph backend start .',
    'cartograph llm smoke .',
    'cartograph doctor .',
    '```',
    '',
    '### Agent server',
    '',
    '```sh',
    'cartograph install --yes --location=local',
    'cartograph serve --mcp --profile coding --project-path .',
    'cartograph serve --mcp --profile core --project-path .',
    'cartograph serve --mcp --profile full --project-path .',
    '```',
    '',
    'Run `cartograph playbook` for the complete MCP tool-selection guide.',
  ].join('\n');
}
