//! Exact v1.1.33 resolved-target parity, complementary to the per-file oracle.
//!
//! All 73 frozen corpora are extracted, accumulated, resolved and canonically
//! validated by the real native pipeline, without PostgreSQL, SCIP or an LLM.
//! This unit-test module uses the same private production boundary as
//! `build_capability_generation`; no test API is added to the shipped library.
//! Every non-containment capture is checked, including same-file relationships.
//! Frozen captures and source bytes are sealed and never regenerated by v2.
//!
//! A fact is uniquely **matched**, explicitly **aligned**, or **ledgered** as
//! pending (wave 2/3 and gap ID) or intentional (reason ID and evidence). Exact
//! repeated captures share a disposition. Nonunique/missing frozen declarations
//! cannot supply an endpoint: such captures require an ambiguity ledger and
//! cannot be matched or aligned. A recorded source line can distinguish frozen
//! owner declarations by their recorded ranges; it cannot distinguish targets.
//!
//! `Pin.key` is an array of readable strings. Frozen keys are
//! `[E, kind, owner-kind, owner-qualified-name, target-file, target-kind,
//! target-qualified-name]`; `site` retains a captured occurrence line if any.
//! Identity substitutes unique captured declaration starts at both endpoints.
//! Canonical native pins are `[E, kind, owner-kind, owner-qualified-name,
//! owner-start, owner-end, target-file, target-kind, target-qualified-name,
//! target-start, target-end]`. File roots use their exact relative path and line
//! 1. End lines disambiguate canonical pins, but are not identity aliases.
//!
//! Observations come from graph edges, not unresolved extraction occurrences.
//! Recorded sites must be backed by a reference with the SAME resolved endpoints
//! and edge kind. A line-less capture can name a derived edge (notably `tests`).
//! All graph observations and all declaration-key collisions are retained;
//! selecting one of several readable endpoints is never an identity match.
//!
//! The sorted, compact JSONL tables in `tests/fixtures/v1_resolution/` hold
//! alignments (conjunctive canonical pins with a reason), divergences, shared
//! reasons, and gate cases. Unknown facts, duplicate dispositions, missing or
//! unused reasons, wrong waves, empty/duplicate/overlapping pins, ambiguous pins,
//! and now-successful identity rows fail. Corrected v1 misresolutions are
//! intentional with source evidence, never aligned to a different target.
//!
//! Run `cargo test --locked -p cartograph-indexer v1_resolution_oracle --
//! --nocapture`. Failures include up to three same-file candidate pins; these
//! are diagnostics only. Verify source, frozen endpoints and real native edges
//! before adding explicit rows. Remove stale rows and unused reasons after a
//! resolver fix. The ignored inventory test prints evidence without writing
//! tables. Mutation tests delete/retarget real resolved edges through this gate.

use super::super::*;
use serde::{Deserialize, Serialize, de::DeserializeOwned};
use std::{collections::BTreeSet, fs, path::Path, sync::OnceLock};

/// Immutable extraction corpora; this oracle owns no copies of their captures.
const CORPORA: &str = concat!(
    env!("CARGO_MANIFEST_DIR"),
    "/../cartograph-extract/tests/fixtures/v1_parity"
);
/// Resolution policy, separate from occurrence-only extraction policy.
const POLICY: &str = concat!(env!("CARGO_MANIFEST_DIR"), "/tests/fixtures/v1_resolution");
/// Released capture binary's immutable SHA-256.
const BINARY: &str = "c223ca62ad1a31f2686c7e79f7175fde440e7f98135062eb3ed8f09937b7e5c7";
/// BLAKE3 of sorted corpus paths, bytes and capture bytes (length-prefixed).
const SEAL: &str = "68b6efac77126d35d625d9cce8637de2456d2684992d963ba3644471d0df1495";
/// Total frozen resolution records, including repeated captures.
const RAW_FACTS: usize = 1_730;

/// Exact frozen declaration, with no fabricated target site.
#[derive(Clone, Deserialize, Eq, Ord, PartialEq, PartialOrd)]
#[serde(deny_unknown_fields)]
struct V1Symbol {
    file: String,
    kind: String,
    name: String,
    qualified_name: String,
    start_line: u32,
    end_line: u32,
}

/// Exact captured resolved edge; occurrence lines remain optional evidence.
#[derive(Deserialize)]
#[serde(deny_unknown_fields)]
struct V1Edge {
    file: String,
    kind: String,
    source_kind: String,
    source: String,
    target_kind: String,
    target: String,
    target_file: String,
    line: Option<u32>,
}

/// Complete capture header and facts, checked against the extraction baseline.
#[derive(Deserialize)]
#[serde(deny_unknown_fields)]
struct Oracle {
    baseline: String,
    binary_sha256: String,
    language: String,
    files: Vec<String>,
    symbols: Vec<V1Symbol>,
    edges: Vec<V1Edge>,
    unresolved: Vec<V1Unresolved>,
}

/// Retain the other frozen records for strict capture and file validation.
#[derive(Deserialize)]
#[serde(deny_unknown_fields)]
struct V1Unresolved {
    file: String,
    kind: String,
    name: String,
    line: Option<u32>,
}

/// Readable exact selector, with an optional source occurrence requirement.
#[derive(Clone, Debug, Deserialize, Serialize, Eq, Ord, PartialEq, PartialOrd)]
#[serde(deny_unknown_fields)]
struct Pin {
    key: Vec<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    site: Option<u32>,
}

/// Frozen selector and its exact identity projection, or capture ambiguity.
#[derive(Clone, Deserialize, Serialize)]
#[serde(deny_unknown_fields)]
struct Fact {
    file: String,
    pin: Pin,
    query: Option<Vec<String>>,
    ambiguity: Option<String>,
}

/// One canonical graph edge and its resolved source-reference sites.
#[derive(Clone, Deserialize, Serialize)]
#[serde(deny_unknown_fields)]
struct Observation {
    file: String,
    key: Vec<String>,
    sites: BTreeSet<u32>,
    identity_unique: bool,
    canonical_unique: bool,
}

/// One corpus's frozen demands and live resolved graph observations.
#[derive(Clone, Deserialize, Serialize)]
#[serde(deny_unknown_fields)]
struct Case {
    language: String,
    captured: Vec<Fact>,
    native: Vec<Observation>,
}

/// Explicit policy for a unique frozen selector.
#[derive(Clone, Deserialize, Serialize, Eq, Ord, PartialEq, PartialOrd)]
#[serde(deny_unknown_fields, tag = "status", rename_all = "snake_case")]
enum Disposition {
    Aligned { pins: Vec<Pin>, id: String },
    Pending { wave: u8, id: String },
    Intentional { id: String },
}

impl Disposition {
    /// Shared evidence identifier, including representation alignments.
    fn id(&self) -> &str {
        match self {
            Self::Aligned { id, .. } | Self::Pending { id, .. } | Self::Intentional { id } => id,
        }
    }
}

/// Ledger row; alignments are stored separately with the same typed contract.
#[derive(Clone, Deserialize, Serialize, Eq, Ord, PartialEq, PartialOrd)]
#[serde(deny_unknown_fields)]
struct Row {
    language: String,
    file: String,
    fact: Pin,
    disposition: Disposition,
}

/// Evidence stored once, with waves only for pending gaps.
#[derive(Clone, Deserialize, Serialize, Eq, Ord, PartialEq, PartialOrd)]
#[serde(deny_unknown_fields)]
struct Definition {
    id: String,
    reason: String,
    wave: Option<u8>,
}

/// Explicit dispositions and shared evidence.
#[derive(Clone, Default, Deserialize)]
#[serde(deny_unknown_fields)]
struct Policy {
    rows: Vec<Row>,
    definitions: Vec<Definition>,
}

/// Small, adversarial gate input and expected diagnostic fragments.
#[derive(Deserialize)]
#[serde(deny_unknown_fields)]
struct Example {
    name: String,
    cases: Vec<Case>,
    policy: Policy,
    problems: Vec<String>,
}

/// Gate counts, failures, and actual carried graph edges for mutation sampling.
#[derive(Default)]
struct Outcome {
    problems: Vec<String>,
    counts: BTreeMap<String, usize>,
    carried: BTreeMap<(usize, usize), Vec<usize>>,
}

/// Full frozen selector shared by deduplication and disposition lookup.
type FactKey<'a> = (&'a str, &'a str, &'a Pin);

/// One captured fact and the native corpus against which its policy is checked.
struct FactCheck<'a> {
    case: &'a Case,
    fact: &'a Fact,
    key: FactKey<'a>,
}

/// Surface original test input failures without hiding their cause.
fn must<T, E: std::fmt::Display>(value: Result<T, E>) -> T {
    value.unwrap_or_else(|error| panic!("{error}"))
}

/// Typed deserialization rejects misspelled policy fields.
fn parse<T: DeserializeOwned>(text: &str) -> T {
    must(serde_json::from_str(text))
}

/// Read one object per line, retaining compact records for review.
fn jsonl<T: DeserializeOwned>(name: &str) -> Vec<T> {
    must(fs::read_to_string(Path::new(POLICY).join(name)))
        .lines()
        .map(parse)
        .collect()
}

/// Enumerate all immutable files, including hidden extraction inputs.
fn paths(root: &Path) -> Vec<String> {
    let mut directories = vec![root.to_path_buf()];
    let mut files = Vec::new();
    while let Some(directory) = directories.pop() {
        for entry in must(fs::read_dir(directory)) {
            let path = must(entry).path();
            if path.is_dir() {
                directories.push(path);
            } else {
                files.push(
                    must(path.strip_prefix(root))
                        .to_string_lossy()
                        .replace('\\', "/"),
                );
            }
        }
    }
    files.sort();
    files
}

/// Seal a framed byte sequence, so path/content boundaries cannot collide.
fn seal_part(hash: &mut blake3::Hasher, bytes: &[u8]) {
    hash.update(&must(u64::try_from(bytes.len())).to_le_bytes());
    hash.update(bytes);
}

/// Unique captured endpoint; a source occurrence may distinguish owner ranges.
fn endpoint(oracle: &Oracle, edge: &V1Edge, target: bool) -> Option<Vec<String>> {
    let (file, kind, name) = if target {
        (&edge.target_file, &edge.target_kind, &edge.target)
    } else {
        (&edge.file, &edge.source_kind, &edge.source)
    };
    let mut symbols = oracle
        .symbols
        .iter()
        .filter(|symbol| {
            &symbol.file == file && &symbol.kind == kind && &symbol.qualified_name == name
        })
        .collect::<BTreeSet<_>>();
    if symbols.len() > 1
        && !target
        && let Some(line) = edge.line
    {
        symbols.retain(|symbol| (symbol.start_line..=symbol.end_line).contains(&line));
    }
    let symbol = symbols.first().filter(|_| symbols.len() == 1)?;
    let (name, start) = if kind == "file" {
        (file, 1)
    } else {
        (name, symbol.start_line)
    };
    Some(vec![kind.clone(), name.clone(), start.to_string()])
}

/// Preserve raw selectors, substituting starts only for uniquely captured endpoints.
fn captured(oracle: &Oracle) -> Vec<Fact> {
    oracle
        .edges
        .iter()
        .filter(|edge| edge.kind != "contains" || edge.target_file != edge.file)
        .map(|edge| {
            let owner = endpoint(oracle, edge, false);
            let target = endpoint(oracle, edge, true);
            let ambiguity = if owner.is_none() {
                Some("ambiguous-v1-owner".into())
            } else if target.is_none() {
                Some("ambiguous-v1-target".into())
            } else {
                None
            };
            let query = owner.zip(target).map(|(owner, target)| {
                let mut key = vec!["E".into(), edge.kind.clone()];
                key.extend(owner);
                key.push(edge.target_file.clone());
                key.extend(target);
                key
            });
            Fact {
                file: edge.file.clone(),
                pin: Pin {
                    key: vec![
                        "E".into(),
                        edge.kind.clone(),
                        edge.source_kind.clone(),
                        edge.source.clone(),
                        edge.target_file.clone(),
                        edge.target_kind.clone(),
                        edge.target.clone(),
                    ],
                    site: edge.line,
                },
                query,
                ambiguity,
            }
        })
        .collect()
}

/// Canonical native declaration component, with file-root scope normalized explicitly.
fn node(symbol: &SymbolInput) -> Vec<String> {
    let (start, end) = if symbol.symbol_kind == "file" {
        (1, 1)
    } else {
        (symbol.start_line, symbol.end_line)
    };
    vec![
        symbol.symbol_kind.clone(),
        symbol.qualified_name.clone(),
        start.to_string(),
        end.to_string(),
    ]
}

/// Identity projection drops only native declaration end lines.
fn alias(key: &[String]) -> Vec<String> {
    key.iter()
        .enumerate()
        .filter(|(i, _)| ![5, 10].contains(i))
        .map(|(_, part)| part.clone())
        .collect()
}

/// Project actual edges; occurrence evidence requires identical resolved endpoints and kind.
fn native(
    facts: &CanonicalGenerationFacts,
    edges: &[EdgeInput],
    sources: &BTreeMap<String, String>,
) -> Vec<Observation> {
    let files = facts
        .files()
        .iter()
        .map(|file| (&file.file_id, file.normalized_path.as_str()))
        .collect::<BTreeMap<_, _>>();
    let symbols = facts
        .symbols()
        .iter()
        .map(|symbol| (&symbol.symbol_id, symbol))
        .collect::<BTreeMap<_, _>>();
    assert_eq!(
        symbols.len(),
        facts.symbols().len(),
        "duplicate native symbol ID"
    );
    let mut canonical = BTreeMap::<_, usize>::new();
    let mut identities = BTreeMap::<_, usize>::new();
    for symbol in facts.symbols() {
        let pin = node(symbol);
        *canonical
            .entry((files[&symbol.file_id], pin.clone()))
            .or_default() += 1;
        *identities
            .entry((files[&symbol.file_id], pin[..3].to_vec()))
            .or_default() += 1;
    }
    edges
        .iter()
        .filter(|edge| edge.kind != EdgeKind::Contains)
        .map(|edge| {
            let owner = symbols[&edge.source_symbol_id];
            let target = symbols[&edge.target_symbol_id];
            let owner_file = files[&owner.file_id];
            let target_file = files[&target.file_id];
            let owner_key = node(owner);
            let target_key = node(target);
            let identity_unique = identities[&(owner_file, owner_key[..3].to_vec())] == 1
                && identities[&(target_file, target_key[..3].to_vec())] == 1;
            let canonical_unique = canonical[&(owner_file, owner_key.clone())] == 1
                && canonical[&(target_file, target_key.clone())] == 1;
            let mut key = vec!["E".into(), edge.kind.as_str().into()];
            key.extend(owner_key);
            key.push(target_file.into());
            key.extend(target_key);
            let sites = facts
                .references()
                .iter()
                .filter(|reference| {
                    let source_id = reference
                        .owner_symbol_id
                        .as_ref()
                        .unwrap_or(&owner.symbol_id);
                    reference.file_id == owner.file_id
                        && source_id == &owner.symbol_id
                        && reference.target_symbol_id.as_ref() == Some(&target.symbol_id)
                        && reference_edge_kind(
                            parse::<ReferenceKind>(&format!("\"{}\"", reference.reference_kind)),
                            parse::<SymbolKind>(&format!("\"{}\"", target.symbol_kind)),
                            Some(parse::<SymbolKind>(&format!("\"{}\"", owner.symbol_kind))),
                        ) == Some(edge.kind)
                        && (reference.owner_symbol_id.is_some() || owner.symbol_kind == "file")
                })
                .map(|reference| {
                    let offset = must(usize::try_from(reference.start_byte));
                    let source = &sources[owner_file];
                    assert!(offset <= source.len());
                    must(u32::try_from(source[..offset].matches('\n').count() + 1))
                })
                .collect();
            Observation {
                file: owner_file.into(),
                key,
                sites,
                identity_unique,
                canonical_unique,
            }
        })
        .collect()
}

/// Exercise the capability helper's real extraction/resolution/reduction boundary at this corpus root.
fn generation(root: &Path, sources: &BTreeMap<String, String>) -> CanonicalGenerationFacts {
    let limits = must(SourceLimits::new(1_024 * 1_024));
    let maximum_bytes = 64 * 1_024 * 1_024;
    let mut accumulator = NativeFactAccumulator::new(maximum_bytes);
    for (path, source) in sources {
        // Manifests and unknown source files stay sealed, but only admitted snapshots parse.
        let snapshot = match SourceSnapshot::from_bytes(path, source.as_bytes(), limits) {
            Ok(snapshot) => snapshot,
            Err(cartograph_extract::SnapshotError::UnsupportedLanguage) => continue,
            Err(error) => panic!("{path}: {error}"),
        };
        let file = must(
            NativeExtractor::new(snapshot.language())
                .and_then(|mut extractor| extractor.extract(&snapshot)),
        );
        must(
            accumulator
                .push(file)
                .map_err(|_| "oracle accumulation budget exceeded"),
        );
    }
    let (facts, _) = must(
        resolve_generation(
            ResolveGenerationRequest {
                extracted: accumulator,
                maximum_bytes,
                source_root: must(SourceRoot::open(root)),
                evidence_policy: NativeEvidencePolicy::FULL,
                clone_policy: NativeClonePolicy {
                    wider_partial_band: false,
                },
            },
            || false,
        )
        .map_err(|_| "oracle resolution budget exceeded"),
    );
    must(validate_generation_facts(
        facts,
        must(generation_validation_limits(
            maximum_bytes,
            PipelineStage::Reduce,
        )),
        || false,
    ))
    .0
}

/// Frozen headers/membership/bytes and live graph evidence, cached for all gate entry points.
fn corpus() -> &'static (Vec<Case>, Policy) {
    static CORPUS: OnceLock<(Vec<Case>, Policy)> = OnceLock::new();
    CORPUS.get_or_init(|| {
        let mut hash = blake3::Hasher::new();
        let mut cases = Vec::new();
        let mut raw = 0;
        let mut total = 0;
        let languages = SourceLanguage::ALL
            .into_iter()
            .filter(|language| language.is_v1_language())
            .collect::<Vec<_>>();
        assert_eq!(languages.len(), 73);
        assert_eq!(paths(&Path::new(CORPORA).join("expected")).len(), 73);
        for language in languages {
            let name = language.as_str();
            let root = Path::new(CORPORA).join(name);
            let capture = must(fs::read_to_string(
                Path::new(CORPORA).join(format!("expected/{name}.json")),
            ));
            seal_part(&mut hash, name.as_bytes());
            seal_part(&mut hash, capture.as_bytes());
            let oracle: Oracle = parse(&capture);
            assert_eq!(
                (
                    oracle.baseline.as_str(),
                    oracle.binary_sha256.as_str(),
                    oracle.language.as_str()
                ),
                ("v1.1.33", BINARY, name)
            );
            let files = paths(&root);
            let visible = files
                .iter()
                .filter(|path| !path.rsplit('/').next().unwrap_or_default().starts_with('.'))
                .cloned()
                .collect::<Vec<_>>();
            assert_eq!(visible, oracle.files, "{name} corpus membership changed");
            let fact_files = oracle
                .symbols
                .iter()
                .map(|symbol| &symbol.file)
                .chain(
                    oracle
                        .edges
                        .iter()
                        .flat_map(|edge| [&edge.file, &edge.target_file]),
                )
                .chain(oracle.unresolved.iter().map(|reference| &reference.file));
            assert!(
                fact_files.into_iter().all(|file| files.contains(file)),
                "missing captured endpoint file"
            );
            assert!(
                oracle
                    .unresolved
                    .iter()
                    .all(|reference| !reference.kind.is_empty()
                        && !reference.name.is_empty()
                        && reference.line.is_none_or(|line| line > 0))
            );
            let sources = files
                .into_iter()
                .map(|path| {
                    let source = must(fs::read_to_string(root.join(&path)));
                    seal_part(&mut hash, path.as_bytes());
                    seal_part(&mut hash, source.as_bytes());
                    (path, source)
                })
                .collect::<BTreeMap<_, _>>();
            total += oracle.symbols.len() + oracle.edges.len() + oracle.unresolved.len();
            let captured = captured(&oracle);
            raw += captured.len();
            let facts = generation(&root, &sources);
            cases.push(Case {
                language: name.into(),
                captured,
                native: native(&facts, facts.edges(), &sources),
            });
        }
        assert_eq!((raw, total), (RAW_FACTS, 8_231));
        assert_eq!(
            hash.finalize().to_hex().as_str(),
            SEAL,
            "frozen corpus/capture bytes changed"
        );
        (cases, load_policy())
    })
}

/// Load distinct alignment and ledger tables, retaining their enforced roles.
fn load_policy() -> Policy {
    let mut rows = jsonl::<Row>("alignments.jsonl");
    assert!(
        rows.iter()
            .all(|row| matches!(row.disposition, Disposition::Aligned { .. }))
    );
    let divergences = jsonl::<Row>("divergences.jsonl");
    assert!(
        divergences
            .iter()
            .all(|row| !matches!(row.disposition, Disposition::Aligned { .. }))
    );
    rows.extend(divergences);
    Policy {
        rows,
        definitions: jsonl("reasons.jsonl"),
    }
}

/// Select exactly one full readable native pin; every recorded site must exist.
fn select(case: &Case, file: &str, pin: &Pin, identity: bool) -> Vec<usize> {
    case.native
        .iter()
        .enumerate()
        .filter(|(_, observation)| {
            observation.file == file
                && pin
                    .site
                    .is_none_or(|site| observation.sites.contains(&site))
                && if identity {
                    observation.identity_unique && alias(&observation.key) == pin.key
                } else {
                    observation.canonical_unique && observation.key == pin.key
                }
        })
        .map(|(index, _)| index)
        .collect()
}

/// Frozen ambiguity always abstains; native graph/site keys must agree exactly.
fn identity(case: &Case, fact: &Fact) -> Vec<usize> {
    if fact.ambiguity.is_some() {
        return Vec::new();
    }
    fact.query.as_ref().map_or_else(Vec::new, |key| {
        select(
            case,
            &fact.file,
            &Pin {
                key: key.clone(),
                site: fact.pin.site,
            },
            true,
        )
    })
}

/// Three same-file candidate pins, sorted deterministically, for human inspection only.
fn suggestions(case: &Case, fact: &Fact) -> String {
    let mut candidates = case
        .native
        .iter()
        .filter(|observation| observation.file == fact.file)
        .collect::<Vec<_>>();
    candidates.sort_by_key(|observation| (observation.key[1] != fact.pin.key[1], &observation.key));
    let pins = candidates
        .into_iter()
        .take(3)
        .map(|observation| (&observation.key, &observation.sites))
        .collect::<Vec<_>>();
    format!("; candidate pins {pins:?}")
}

/// Validate shared reasons while building their disposition lookup.
fn policy_definitions<'a>(
    policy: &'a Policy,
    outcome: &mut Outcome,
) -> BTreeMap<&'a str, &'a Definition> {
    let mut definitions = BTreeMap::new();
    for definition in &policy.definitions {
        if definition.id.trim().is_empty()
            || definition.reason.trim().is_empty()
            || definition.wave.is_some_and(|wave| ![2, 3].contains(&wave))
            || definitions
                .insert(definition.id.as_str(), definition)
                .is_some()
        {
            outcome
                .problems
                .push(format!("invalid/duplicate definition {}", definition.id));
        }
    }
    definitions
}

/// Reject invalid rows and reasons before any native correspondence is considered.
fn policy_rows<'a>(
    cases: &[Case],
    policy: &'a Policy,
    outcome: &mut Outcome,
) -> BTreeMap<FactKey<'a>, &'a Disposition> {
    let definitions = policy_definitions(policy, outcome);
    let captured = cases
        .iter()
        .flat_map(|case| {
            case.captured
                .iter()
                .map(|fact| (case.language.as_str(), fact.file.as_str(), &fact.pin))
        })
        .collect::<BTreeSet<_>>();
    let mut rows = BTreeMap::new();
    let mut used = BTreeSet::new();
    for row in &policy.rows {
        let key = (row.language.as_str(), row.file.as_str(), &row.fact);
        if !captured.contains(&key) {
            outcome.problems.push(format!("unknown v1 fact {key:?}"));
        }
        if rows.insert(key, &row.disposition).is_some() {
            outcome
                .problems
                .push(format!("two dispositions for {key:?}"));
        }
        let id = row.disposition.id();
        used.insert(id);
        let wave = match row.disposition {
            Disposition::Pending { wave, .. } => Some(wave),
            _ => None,
        };
        if definitions
            .get(id)
            .is_none_or(|definition| definition.wave != wave)
        {
            outcome
                .problems
                .push(format!("undefined or wrong-wave id {id}"));
        }
        if let Disposition::Aligned { pins, .. } = &row.disposition
            && (pins.is_empty() || pins.iter().collect::<BTreeSet<_>>().len() != pins.len())
        {
            outcome
                .problems
                .push(format!("empty/duplicate pins for {key:?}"));
        }
    }
    for id in definitions.keys().filter(|id| !used.contains(**id)) {
        outcome.problems.push(format!("unused definition {id}"));
    }
    rows
}

impl FactCheck<'_> {
    /// Classify one unique frozen fact and retain its carried native observations.
    fn classify(
        &self,
        rows: &BTreeMap<FactKey<'_>, &Disposition>,
        outcome: &mut Outcome,
    ) -> (String, Vec<usize>) {
        let key = self.key;
        let matches = identity(self.case, self.fact);
        let row = rows.get(&key);
        let mut carried = Vec::new();
        let status = if matches.len() == 1 {
            if row.is_some() {
                outcome.problems.push(format!("stale/redundant {key:?}"));
            }
            carried = matches;
            "matched".into()
        } else if let Some(ambiguity) = &self.fact.ambiguity {
            if !matches!(row, Some(Disposition::Intentional { id }) if id == ambiguity) {
                outcome.problems.push(format!(
                    "capture ambiguity requires {ambiguity} ledger for {key:?}"
                ));
            }
            format!("intentional:{ambiguity}")
        } else {
            match row {
                Some(Disposition::Aligned { pins, .. }) => {
                    carried.extend(self.alignment_targets(pins, outcome));
                    "aligned".into()
                }
                Some(Disposition::Pending { wave, id }) => format!("pending-wave-{wave}:{id}"),
                Some(Disposition::Intentional { id }) => format!("intentional:{id}"),
                None => {
                    outcome.problems.push(format!(
                        "unmatched/ambiguous {key:?}; native observations {matches:?}{}",
                        suggestions(self.case, self.fact)
                    ));
                    "unmatched".into()
                }
            }
        };
        (status, carried)
    }

    /// Select conjunctive alignment pins and report missing or overlapping targets.
    fn alignment_targets(&self, pins: &[Pin], outcome: &mut Outcome) -> BTreeSet<usize> {
        let key = self.key;
        let mut selected = BTreeSet::new();
        for pin in pins {
            let found = select(self.case, &self.fact.file, pin, false);
            if let [index] = found.as_slice() {
                if !selected.insert(*index) {
                    outcome
                        .problems
                        .push(format!("overlapping pins for {key:?}"));
                }
            } else {
                outcome.problems.push(format!(
                    "missing/ambiguous pin for {key:?}: {pin:?}{}",
                    suggestions(self.case, self.fact)
                ));
            }
        }
        selected
    }
}

/// Run the complete gate on arbitrary inputs and real corpora alike.
fn check(cases: &[Case], policy: &Policy) -> Outcome {
    let mut outcome = Outcome::default();
    let rows = policy_rows(cases, policy, &mut outcome);
    for (case_index, case) in cases.iter().enumerate() {
        let mut counted = BTreeSet::new();
        for (fact_index, fact) in case.captured.iter().enumerate() {
            let input = FactCheck {
                case,
                fact,
                key: (case.language.as_str(), fact.file.as_str(), &fact.pin),
            };
            if !counted.insert(input.key) {
                continue;
            }
            let (status, carried) = input.classify(&rows, &mut outcome);
            *outcome.counts.entry(status).or_default() += 1;
            if !carried.is_empty() {
                outcome.carried.insert((case_index, fact_index), carried);
            }
        }
    }
    outcome
}

/// Require clean measurements; a passing ledger does not assert overall parity.
fn verified(cases: &[Case], policy: &Policy) -> Outcome {
    let outcome = check(cases, policy);
    assert!(
        outcome.problems.is_empty(),
        "{}",
        outcome.problems.join("\n")
    );
    outcome
}

/// Every captured resolved target has an exact match, pinned alignment or explicit ledger.
#[test]
fn exact_resolved_targets_or_explicit_dispositions() {
    let (cases, policy) = corpus();
    let outcome = verified(cases, policy);
    println!(
        "{RAW_FACTS} raw facts; {} unique facts; 0 unmatched / 0 stale / 0 problems; {:?}",
        outcome.counts.values().sum::<usize>(),
        outcome.counts
    );
}

/// Typed ordering, compact serialization and duplicate rejection for all policy tables.
fn sorted<T: DeserializeOwned + Serialize + Ord>(name: &str) {
    let text = must(fs::read_to_string(Path::new(POLICY).join(name)));
    let records = jsonl::<T>(name);
    assert!(
        records.windows(2).all(|pair| pair[0] < pair[1]),
        "{name} order"
    );
    for (record, line) in records.iter().zip(text.lines()) {
        assert_eq!(
            must(serde_json::to_string(record)),
            line,
            "{name} compact record"
        );
    }
}

/// Committed tables have deterministic, reviewable formatting.
#[test]
fn compact_tables_are_sorted() {
    sorted::<Row>("alignments.jsonl");
    sorted::<Row>("divergences.jsonl");
    sorted::<Definition>("reasons.jsonl");
}

/// Counterexamples exercise the very same gate as the corpus.
#[test]
fn gate_cases_enforce_exact_targets_and_hygiene() {
    for example in jsonl::<Example>("gate_cases.jsonl") {
        let outcome = check(&example.cases, &example.policy);
        assert_eq!(
            outcome.problems.is_empty(),
            example.problems.is_empty(),
            "{}: {:?}",
            example.name,
            outcome.problems
        );
        for wanted in example.problems {
            assert!(
                outcome
                    .problems
                    .iter()
                    .any(|problem| problem.contains(&wanted)),
                "{}: missing {wanted}: {:?}",
                example.name,
                outcome.problems
            );
        }
    }
}

/// Human-readable inventory only: never generates an expected table or rewrites captures.
#[test]
#[ignore = "prints the complete frozen/live inventory for manual disposition review"]
fn resolution_inventory() {
    let (cases, _) = corpus();
    for case in cases {
        println!("ORACLE_CASE {}", must(serde_json::to_string(case)));
        let root = Path::new(CORPORA).join(&case.language);
        let sources = paths(&root)
            .into_iter()
            .map(|path| {
                let source = must(fs::read_to_string(root.join(&path)));
                (path, source)
            })
            .collect();
        let facts = generation(&root, &sources);
        println!(
            "ORACLE_NATIVE {}",
            json!({
                "language": case.language, "files": facts.files(),
                "symbols": facts.symbols(), "references": facts.references(),
            })
        );
    }
}

/// One deterministic representative of each carried kind and disposition per corpus.
fn mutation_samples(
    case_index: usize,
    case: &Case,
    baseline: &Outcome,
) -> BTreeMap<(String, bool), (usize, usize)> {
    let mut samples = BTreeMap::<_, (usize, usize)>::new();
    for ((carried_case, fact_index), observations) in &baseline.carried {
        if *carried_case != case_index {
            continue;
        }
        let fact = &case.captured[*fact_index];
        let is_aligned = identity(case, fact).len() != 1;
        for observation in observations {
            let native = &case.native[*observation];
            let key = (native.key[1].clone(), is_aligned);
            // Prefer cross-file representatives; sample choice never participates in matching.
            let entry = samples.entry(key).or_insert((*fact_index, *observation));
            if case.native[entry.1].key[6] == case.native[entry.1].file
                && native.key[6] != native.file
            {
                *entry = (*fact_index, *observation);
            }
        }
    }
    samples
}

/// Delete and retarget real carried edges, sampling each corpus/kind/disposition.
#[test]
fn mutations_of_resolved_edges_fail_the_same_gate() {
    let (cases, policy) = corpus();
    let baseline = verified(cases, policy);
    let mut killed = 0;
    let mut tested_edges = 0;
    let mut cross_file = 0;
    let mut aligned = 0;
    for (case_index, case) in cases.iter().enumerate() {
        let samples = mutation_samples(case_index, case, &baseline);
        if samples.is_empty() {
            continue;
        }
        let root = Path::new(CORPORA).join(&case.language);
        let sources = paths(&root)
            .into_iter()
            .map(|path| {
                let source = must(fs::read_to_string(root.join(&path)));
                (path, source)
            })
            .collect();
        let facts = generation(&root, &sources);
        let edges = facts
            .edges()
            .iter()
            .filter(|edge| edge.kind != EdgeKind::Contains)
            .cloned()
            .collect::<Vec<_>>();
        let rows = policy
            .rows
            .iter()
            .filter(|row| row.language == case.language)
            .cloned()
            .collect::<Vec<_>>();
        let ids = rows
            .iter()
            .map(|row| row.disposition.id())
            .collect::<BTreeSet<_>>();
        let local = Policy {
            definitions: policy
                .definitions
                .iter()
                .filter(|definition| ids.contains(definition.id.as_str()))
                .cloned()
                .collect(),
            rows,
        };
        for ((_, is_aligned), (fact_index, edge_index)) in samples {
            let expected = format!(
                "{:?}",
                (
                    case.language.as_str(),
                    case.captured[fact_index].file.as_str(),
                    &case.captured[fact_index].pin
                )
            );
            cross_file +=
                usize::from(case.native[edge_index].key[6] != case.native[edge_index].file);
            aligned += usize::from(is_aligned);
            tested_edges += 1;
            for retarget in [false, true] {
                let mut changed = edges.clone();
                if retarget {
                    let edge = &mut changed[edge_index];
                    let wrong = facts
                        .symbols()
                        .iter()
                        .find(|symbol| {
                            symbol.symbol_id != edge.target_symbol_id
                                && symbol.symbol_id != edge.source_symbol_id
                        })
                        .unwrap_or_else(|| panic!("no alternate mutation target"));
                    edge.target_symbol_id = wrong.symbol_id.clone();
                } else {
                    changed.remove(edge_index);
                }
                let mut mutant = case.clone();
                mutant.native = native(&facts, &changed, &sources);
                let outcome = check(&[mutant], &local);
                assert!(
                    outcome
                        .problems
                        .iter()
                        .any(|problem| problem.contains(&expected)),
                    "surviving mutation: retarget={retarget} {expected}"
                );
                killed += 1;
            }
        }
    }
    assert!(
        tested_edges > 0 && cross_file > 0 && aligned > 0,
        "mutation sample must include cross-file and aligned edges"
    );
    assert_eq!(killed, tested_edges * 2);
    println!(
        "mutation kill rate: {killed}/{}; {tested_edges} edges ({cross_file} cross-file, {aligned} aligned); deletion and retargeting",
        tested_edges * 2
    );
}
